# This action triggers the build hook
name: Schedule Build Hook Trigger

# Controls when the workflow will run
on:
 schedule:
   # Runs at 9am everyday
   - cron: "0 9 * * *"
     
# The workflow to run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Runs a request to the build hook of Vercel
        - name: Build hook request
          run: curl -X POST -d {} ${{ secrets.HOOK }}
